### ISSUE TITLE
FiQA GoogleDrive download link broken.

### ISSUE THREAD

**Issue by zhangzx-uiuc** [awslabs/robustqa-acl23#1]
Thanks for releasing the dataset!

However, it seems that the following google drive link provided in README is broken: 

"Download the raw corpus FiQA_train_doc_final.tsv and question file FiQA_train_question_final.tsv into data/fiqa from https://drive.google.com/file/d/1BlWaV-qVPfpGyJoWQJU9bXQgWCATgxEP/view."

Could you please look into this problem?

Thanks!

**Comment by zhangzx-uiuc** [comment]
Ok it seems that these links are from the official website of FiQA. I am sending out an email to the organizer about this issue.

**Comment by Aakriti28** [comment]
> Ok it seems that these links are from the official website of FiQA. I am sending out an email to the organizer about this issue.

Hi, any luck in getting the correct link to the dataset?

**Comment by logan-markewich** [comment]
Why close this issue? Its impossible to replicate without this dataset 😅
